name: CI

env:
  TZ: 'Asia/Tokyo'

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # テストの準備
      - name: Checkout code
        uses: actions/checkout@v2

      - name: node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: yarn install
        run: yarn install

      # レビュードッグ
      - name: reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{js,jsx,ts,tsx}'

      # 単体テスト & 結合テスト
      - name: test
        run: yarn test
